version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: spring-rest-api-0-db

    ports:
      - 3309:3306

    environment:
      MYSQL_ROOT_PASSWORD: 'toor'
      MYSQL_DATABASE: 'tutorial'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'boot'

    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
